const CatchAsyncError = require("../middleware/catchAsyncError");

const validateCoupon = CatchAsyncError(async (req, res, next) => {});
